/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotesLab;

public class App {
    public static void main(String[] args) {
        System.out.println("Lab 08");
        Qclass q1 = new Qclass();
        q1.randomQ();
    }

}
